### ISSUE TITLE
Info de dimension des groupes non visible

### ISSUE THREAD

**Issue by adrijauf** [jfellus/coeos3#5]
La taille des groupes (simple neurone, vecteur horizontal, vertical, ou matrice) n'est pas visible sur les groupes.
Dans l'ancien coeos, cette info était représentée par un point (neurone unique), 1 fleche (vecteur) ou 2 fleches orthogonales (matrice)

**Comment by jfellus** [comment]
La dimension des groupes s'affiche si tu actives View > Display All Infos...
Sinon tu les a quand tu survole un groupe.

Si ca ne s'affiche pas c'est un bug. Est-ce le cas ?

**Comment by adrijauf** [comment]
Ok, ça marche. Mais ce n'est pas ce que je voulais.
Je ne veux pas forcement le nombre total de neurones dans le groupe mais plutot une indication concernant sa dimensionnalité. C'est très utile de "voir" sur le groupe si c'est un neurone unique (un point) ou bien un vecteur colonne (un fleche verticale) ou bien un vecteur ligne (fleche horizontale) ou encore une matrice (double fleche). Tu vois ce que je veux dire ?

**Comment by jfellus** [comment]
Oui, oui, je pense bien !
![image](https://cloud.githubusercontent.com/assets/8638673/5872622/d8e25820-a2ed-11e4-9fc5-630f140a7c6e.png)

Effectivement, il y a un bug dans l'affichage des fleches pour les groupes 10x10, mais la fonctionnalité est bien là, non ? A gauche des width x height ?

Je considère que c'est un bug d'affichage d'arrows ?

**Comment by adrijauf** [comment]
Ahh c'est ça... j'avais pas compris. 
Ok, ça me déroute un peu je t'avoue (surement parce que je suis maintenant un vieux con de promethe). 
Quand je regarde un script de loin, j'ai besoin que la dimensionnalité me saute aux yeux pour pouvoir bien comprendre ce que je fais ou quels groupes peuvent etre fusionnés ou pas... 
Du coup, pour moi, le top du top of the pop ce serait d'avoir des "formes" de groupe différentes, du style: 
- un groupe en forme de rond (comme tu l'as fais) désigne un neurone unique.
- un rectangle horizontale ou verticale désigne un vecteur selon respectivement x ou y
- un carré (comme tu l'as fais pour les groupes "neuronaux") désignerait une matrice

**Comment by adrijauf** [comment]
![coeos](https://cloud.githubusercontent.com/assets/10657858/5873336/871295ca-a2f5-11e4-8461-c1ff1464b73f.png)

**Comment by jfellus** [comment]
J'avoue ! J'y avais même pas pensé !
Je peux tout simplement mettre une règle CSS qui dit en gros 

module.2D { svg:bla.svg }
module.1Dh { svg:bla1.svg }
module.1Dv { svg:bla2.svg }
module.scalar { svg:rond.svg}

C'est faisable. 
Je peux même mettre si c'est carré ou non (attention, je peux pas inferrer plus que ((string)width)==((string)height) dans le .symb ! c'est à dire si tu as "width=VAR1" et "height=VAR2" et que dans le .var VAR1==VAR2, il dira pas carré. De toute façon, il dira que la matrice est rectangle même si VAR1=1 et VAR2=200000...

Mais c'est une bonne idée de mettre du CSS different pour les tailles differentes. Je pense que je vais faire ça. Ca te plait ?

**Comment by adrijauf** [comment]
Grave

**Comment by jfellus** [comment]
bon bah je l'ai mis en TODO.
Dès que j'ai du temps j'attaque tout ça

**Comment by jfellus** [comment]
C'est fait. Est-ce que ça convient ?
(je fais biensur l'hypothèse que si les dimensions d'un groupe sont des variables, alors on suppose que c'est different de 1. Exemple : 1xMAVAR => 1xN).

Ca serait bien qu'à terme on converge vers un style "papier-izable" qui puisse facilement s'exporter. En l'occurrence avec cairo on peut facilement exporter un pdf. Ce serait pratique de faire des vues directement présentables des modèles sans passer par du tedious inkscape.

![image](https://cloud.githubusercontent.com/assets/8638673/5896654/62e4c682-a539-11e4-9cdf-b21951a61f49.png)
