### ISSUE TITLE
Superposition des scripts

### ISSUE THREAD

**Issue by adrijauf** [jfellus/coeos3#6]
Lorsque l'on ouvre simultanément plusieurs scripts (15 gros scripts dans mon cas), l'interface est inutilisable. Tout les scripts sont superposés et le ralentissement est trop important pour faire quoique ce soit.
Il faudrait revenir à l'usage d'onglets (1 onglet par script), ou bien de freeze (on ne rafraichi pas l'affichage des scripts qui sont en mode "freeze").

**Comment by jfellus** [comment]
Gros probleme : le rendu est confié à cairo et à chaque event la totalité du canvas est re-rendu. C'est différent du rendu de e.g. Inkscape qui bufferize le rendu dans une image offscreen puis la deplace juste quand l'utilisateur navigue. L'image est alors updaté et rerendue que quand une modification l'oblige (mais pas pendant la navigation). Dans coeos++, ce n'est pas le cas pour le moment. Et c'est dur à modifier.

Du coup je propose : à l'ouverture d'un net, si la position des scripts n'est pas spécifiée (cas d'une edition d'un vieux script de coeos_old), les scripts sont dispatchés de sorte à pas avoir d'intersections de bounding boxes. 

A SAVOIR : cairo bypass le rendu d'élements qui sortent de l'ecran. Si tu zoom, tu verra que tu retrouve fluidité et bonheur.

**Comment by jfellus** [comment]
Pour le moment, j'ai fait en sorte que lorsqu'on ouvre un net qui n'a pas d'annotations @closed=???
par defaut le script est "fermé". Comme ca, si tu ouvres un gros .net de l'ancien coeos, par defaut tous
les scripts sont fermés. Tu les ouvres en dbl-clickant dessus. 
Par la suite quand tu sauvegarde, ça sauvegarde la position des scripts et leur etat fermé/ouvert.
Donc plus de pb pour le lag dans le rendu, il suffit de bien etaler ses scripts la 1ere fois et de fermer ceux qui sont trop gros et qu'on edite pas...

ca devrait faire l'affaire pour l'instant, mais c'est vrai que c'est un pb.

A+
