### ISSUE TITLE
numéro du groupe

### ISSUE THREAD

**Issue by adrijauf** [jfellus/coeos3#8]
Lorsqu'on survole un groupe, il affiche son numéro dans un rond bleu. 
Mais parfois les groupes ont un nom complet à la place du numéro et demande donc plus de place pour etre affichés.

**Comment by jfellus** [comment]
Dans mon idée, le no_name est voué à disparraitre en tant que valeur manuellement editable. Aujourd'hui il réalise une double fonction qui est bien débile : 
- attribuer un identifiant unique à un groupe
- donner un nom à un groupe

Or, le coup du nom c'est pas top car pour les groupes neuronaux, les gens mettent le nom dans le champ "groupe". Ca donne une mauvaise pratique car ça disperse cette notion de nom sur plusieurs champs qui n'ont rien à voir.

Dans coeos++ l'approche est différente : il existe un champ "nom" bien identifié qui n'a rien à voir avec no_name ou groupe. Il est sauvegardé comme un annotation dans le .symb. Du coup le no_name n'est qu'un id qui s'incremente quand tu crée ou copie-colle. Pas plus pas moins. Pour les scripts existants, c'est vrai que c'est pas top, mais je tiens à forcer les gens à utiliser le champ "nom" qui s'affiche sous le groupe à coté de son type plutôt que le no_name.

**Comment by adrijauf** [comment]
Completement d'accord
